### ISSUE TITLE
How to manually rebuild project?

### ISSUE THREAD

**Issue by suclogger** [MindMac/AndroidEagleEye#9]
Hi, it is a great project!
  I  tried to add some logic under `hookclass` package(not a native method), but I couldn't figure out how to rebuild an apk file. Could you pls offer some build guide?
Thanks a lot.

**Comment by suclogger** [comment]
Failed to excute ndk build using 13.1.3 .
Which ndk version should be used?

`Android NDK: WARNING: APP_PLATFORM android-19 is larger than android:minSdkVersion 14 in ./AndroidManifest.xml    
[arm64-v8a] Compile        : eagleeyenative <= entry.c
jni/entry.c:16:1: warning: type specifier missing, defaults to 'int' [-Wimplicit-int]
Java_com_mindmac_eagleeye_NativeEntry_initSystemNativeHook( JNIEnv* env, jobject this )
^
jni/entry.c:21:3: error: non-void function 'Java_com_mindmac_eagleeye_NativeEntry_initSystemNativeHook' should return a value [-Wreturn-type]
                return;
                ^
jni/entry.c:28:3: error: non-void function 'Java_com_mindmac_eagleeye_NativeEntry_initSystemNativeHook' should return a value [-Wreturn-type]
                return;
                ^
jni/entry.c:38:31: warning: implicit declaration of function 'getpid' is invalid in C99 [-Wimplicit-function-declaration]
                        if(hook(&(hook_info->eph), getpid(), hook_info->libname, hook_info->funcname,
                                                   ^
jni/entry.c:46:1: warning: type specifier missing, defaults to 'int' [-Wimplicit-int]
Java_com_mindmac_eagleeye_NativeEntry_initCustomNativeHook(JNIEnv* env, jobject this, jstring lib_name){
^
jni/entry.c:53:3: error: non-void function 'Java_com_mindmac_eagleeye_NativeEntry_initCustomNativeHook' should return a value [-Wreturn-type]
                return;
                ^
jni/entry.c:64:3: error: non-void function 'Java_com_mindmac_eagleeye_NativeEntry_initCustomNativeHook' should return a value [-Wreturn-type]
                return;
                ^
jni/entry.c:71:3: error: non-void function 'Java_com_mindmac_eagleeye_NativeEntry_initCustomNativeHook' should return a value [-Wreturn-type]
                return;
                ^
3 warnings and 5 errors generated.
make: *** [obj/local/arm64-v8a/objs/eagleeyenative/entry.o] Error 1
`

**Comment by wbonis** [comment]
I have the same Problem!

**Comment by MindMac** [comment]
@suclogger  The ndk version I used is r10e.

**Comment by nunofaria007** [comment]
# 1 - Create a new .mk file and paste the following text (this will set the correct ABI and toolchain)
APP_PROJECT_PATH := $(NDK_PROJECT_PATH)
APP_ABI := armeabi
NDK_TOOLCHAIN_VERSION = 4.9
ifndef APP_BUILD_SCRIPT
  ifeq (null,$(NDK_PROJECT_PATH))
    $(call __ndk_info,NDK_PROJECT_PATH==null.  Please explicitly set APP_BUILD_SCRIPT.)
    $(call __ndk_error,Aborting.)
  endif
  APP_BUILD_SCRIPT := $(APP_PROJECT_PATH)/jni/Android.mk
endif

## Note
(NDK_TOOLCHAIN_VERSION = 4.9): In my case, a clang toolchain (arm-linux-androideabi-clang) was being used by default, so i had to change it to a gcc one (arm-linux-androideabi-4.9), you can check the version on the /toolchains folder and set this parameter accordingly

# 2- Add following parameter to ndk-build
 NDK_APPLICATION_MK=%Path to the .mk file created in step 1%

**Comment by junges521** [comment]
I have the same Problem!
